global:
  namespace: microservices-demo
  environment: dev

configmap:
  data:
    APP_ENV: "dev"

userService:
  name: user-service
  image: jkliujun/user-service:liuj-dev-20250626011248
  port: 38080
  nodePort: 31080
  imagePullSecret: regcred

orderService:
  name: order-service
  image: jkliujun/order-service:liuj-dev-20250626014427
  port: 38081
  nodePort: 31081
  imagePullSecret: regcred