global:
  namespace: microservices-demo
  environment: dev
configmap:
  data:
    APP_ENV: "dev"
userService:
  name: user-service
  # image: jkliujun/user-service:liuj-dev-20250628024354
  image:
    repository: jkliujun/user-service
    tag: "jenkins-dev-20250628135206"
  port: 38080
  nodePort: 31080
  imagePullSecret: regcred
orderService:
  name: order-service
  # image: jkliujun/order-service:liuj-dev-20250628024354
  image:
    repository: jkliujun/order-service
    tag: "jenkins-dev-20250628135206"
  port: 38081
  nodePort: 31081
  imagePullSecret: regcred
