grpc:
  server:
    port: 48000
server:
  port: 38080  
spring:
  application:
    name: grpc-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.76.174:8848
        enabled: true
        port: 48000
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
