grpc:
  client:
    grpc-user-service:
      # address: static://127.0.0.1:48000
      negotiationType: plaintext
server:
  port: 38081
spring:
  application:
    name: grpc-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.76.174:8848
        enabled: true
        port: 38081
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
