apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.orderService.port }}
      targetPort: {{ .Values.orderService.port }}
      nodePort: {{ .Values.orderService.nodePort }}
  selector:
    app: {{ .Values.orderService.name }}