apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.userService.port }}
      targetPort: {{ .Values.userService.port }}
      nodePort: {{ .Values.userService.nodePort }}
  selector:
    app: {{ .Values.userService.name }}