apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.userService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.userService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.userService.name }}
    spec:
      containers:
        - name: user
          image: {{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}
          ports:
            - containerPort: {{ .Values.userService.port }}
          envFrom:
            - configMapRef:
                name: microservices-demo-env
      imagePullSecrets:
        - name: {{ .Values.userService.imagePullSecret }}